### ISSUE TITLE
Outdated build instructions

### ISSUE THREAD

**Issue by olofk** [embecosm/chiphack#1]
Much has happened since these build instructions at https://github.com/embecosm/chiphack/wiki/OpenRISC-tools-install were written. I just got a user who had some trouble with them, and I suggest that much of the contents should be removed, and replaced by links instead

To be more specific,

The build instructions for the OpenRISC bare-metal toolchain is available at http://openrisc.io/newlib/building.html and the instructions for installing FuseSoC can be found at https://github.com/olofk/fusesoc

**Comment by juliusbaxter** [comment]
On 10 March 2017 at 09:04, Olof Kindgren <notifications@github.com> wrote:

> Much has happened since these build instructions at
> https://github.com/embecosm/chiphack/wiki/OpenRISC-tools-install were
> written. I just got a user who had some trouble with them, and I suggest
> that much of the contents should be removed, and replaced by links instead
>
> To be more specific,
>
> The build instructions for the OpenRISC bare-metal toolchain is available
> at http://openrisc.io/newlib/building.html and the instructions for
> installing FuseSoC can be found at https://github.com/olofk/fusesoc
>
I don't see why not. This shouldn't impact the tutorial, right?

Julius

**Comment by jeremybennett** [comment]
Olof - would you like to provide a patch to update the instructions and I'll merge it. Thanks

**Comment by olofk** [comment]
Not sure how to send patches for the wiki. I could try to edit the page if I have permissions

**Comment by olofk** [comment]
Apparently, I had write access to the wiki. Please review and revert if you're not happy with the changes. I decided against duplicating the toolchain instructions from the link, as they might be outdated in a while when we get gdb properly upstreamed

**Comment by jeremybennett** [comment]
Many thanks for fixing this.
