### ISSUE TITLE
Errors during installation of openrisc toolchain-make command in newlib

### ISSUE THREAD

**Issue by bhatmahadev6** [embecosm/chiphack#20]
Makefile:1031: recipe for target 'libc.a' failed
make[5]: *** [libc.a] Error 127
make[5]: Leaving directory '/home/mahadev/or1k/build-newlib/or1k-elf/newlib/libc'
Makefile:683: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/mahadev/or1k/build-newlib/or1k-elf/newlib/libc'
Makefile:641: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/mahadev/or1k/build-newlib/or1k-elf/newlib'
Makefile:452: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/mahadev/or1k/build-newlib/or1k-elf/newlib'
Makefile:8491: recipe for target 'all-target-newlib' failed
make[1]: *** [all-target-newlib] Error 2
make[1]: Leaving directory '/home/mahadev/or1k/build-newlib'
Makefile:878: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jeremybennett** [comment]
General questions like this are best directed to the OpenRISC mailing list at librecores.org (https://lists.librecores.org/listinfo/openrisc). You should include the complete set of commands you issued and attach the log file to your question.
